# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "ioxbank-btsexchange" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [13.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: npm run build
            - uses: actions/upload-artifact@v2
              with:
                name: bitshares-ui
                path: build/dist/ # or path/to/artifact
