# This workflow will do a clean install of node dependencies, build the source code and push the binaries to the deployment repository.
name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build
            - name: Step 1 - Create a temporary artifact downloads folder
                run: mkdir downloads
            - name: step 2 - Add artifacts to publish to the temp folder
              run: |
                 cp -r bitshares-ui/build/dist/* downloads
                 cd ..
            - name: Step 3 - Use the Upload Artifact GitHub Action
                uses: actions/upload-artifact@v2
                with: 
                  name: assets-for-download
                  path: downloads
